server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: Driver
      password: start
  application:
    name: Driver
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: Driver
    password: ""
    schema: classpath:schema.sql
    data : classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      hbm2ddl:
        auto : update

    #    properties:
#      hibernate:
#        format_sql : true

    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type:
          descriptor:
            sql: TRACE



  logging:
    level:
      org.springframework.cloud.openfeign: DEBUG

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


  instance:
    hostname: localhost

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
